// vendor
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

// styles
import './globals.css'
import css from './page.module.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface IProps {
  children: React.ReactNode
}

async function RootLayout({ children }: IProps) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <main className={css.main}>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  )
}

export default RootLayout
