// vendor
import type { Metadata } from 'next'
import {
  Inter,
  Dosis,
  Jost,
  Hind,
  Encode_Sans,
  IBM_Plex_Sans,
} from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

// styles
import './reset.css'
import './globals.css'
import css from './page.module.scss'

const font = IBM_Plex_Sans({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface IProps {
  children: React.ReactNode
}

async function RootLayout({ children }: IProps) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={font.className}>
          <main className={css.main}>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  )
}

export default RootLayout
